[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "squardle_solver"
version = "0.0.1"

[project.scripts]
squardle-solve = "squardle_solver.solve:main_cli"
